### ISSUE TITLE
Implement experience system and add color adding

### ISSUE THREAD

**Issue by EliasHaaralahti** [EliasHaaralahti/No-Mans-Canvas-Client#4]
Implement experience system, allow adding colors after reaching max experience required. If not yet done, max experience should also be retrieved from backend. Also possibly max tile count.

**Comment by vkoskiv** [comment]
Color adding would get really complicated, really fast. The EXP system pretty much serves as another form of rate-limiting to prevent newly generated accounts from being able to spam too much right away.
The level progress logic could use some work, though.
